# Generated by Django 4.2.7 on 2023-11-20 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('asset_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=48)),
                ('img_url', models.URLField(default='default_logo.png')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('org_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=48)),
                ('address', models.CharField(max_length=255)),
                ('org_type', models.CharField(choices=[('H', 'Hospital'), ('S', 'Supplier')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('dest_org_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='dest_org_id', to='mainapp.organization')),
                ('src_org_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='src_org_id', to='mainapp.organization')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('asset_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.asset')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.purchaseorder')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_unit', models.IntegerField()),
                ('qty_available', models.IntegerField()),
                ('asset_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.asset')),
                ('org_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.organization')),
            ],
        ),
    ]
