# Generated by Django 4.2.7 on 2023-11-27 10:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_purchaseorder_approval_status_purchaseorder_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 27, 15, 40, 6, 331915)),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='updated_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 27, 15, 40, 6, 331915)),
        ),
    ]
