# Generated by Django 4.2.7 on 2023-11-27 10:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_purchaseorder_created_on_purchaseorder_updated_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='approval_status',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='updated_on',
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 27, 16, 5, 20, 939963)),
        ),
    ]
